Script started on 2023-02-08 11:50:37-05:00 [TERM="xterm-256color" TTY="/dev/pts/40" COLUMNS="84" LINES="33"]
]0;oarbelwo@compute:~/courses/cs2211/Asn/asn2[?2004h[oarbelwo@compute asn2]$ date
[?2004lWed 08 Feb 2023 11:50:40 AM EST
]0;oarbelwo@compute:~/courses/cs2211/Asn/asn2[?2004h[oarbelwo@compute asn2]$ whoami
[?2004loarbelwo
]0;oarbelwo@compute:~/courses/cs2211/Asn/asn2[?2004h[oarbelwo@compute asn2]$ pwd
[?2004l/home/oarbelwo/courses/cs2211/Asn/asn2
]0;oarbelwo@compute:~/courses/cs2211/Asn/asn2[?2004h[oarbelwo@compute asn2]$ ls
[?2004l[0m[01;32mconverter[0m    converter.script  exp_calculator.c
converter.c  [01;32mexp_calculator[0m    exp_calculator.script
]0;oarbelwo@compute:~/courses/cs2211/Asn/asn2[?2004h[oarbelwo@compute asn2]$ ./exp_calculator [K
[?2004lEnter the base (non-zero double): 0, .00001
Enter the exponent (integer): 4
Result is : 0.00000000000000000001
Enter the base (non-zero double): 23
Enter the exponent (integer): 4
Result is : 279841.00000000000000000000
Enter the base (non-zero double): 0.0023
Enter the exponent (integer): 19
Result is : 0.00000000000000000000
Enter the base (non-zero double): ^[[A    0.32
Enter the exponent (integer): 5
Result is : 0.00335544320000000012
Enter the base (non-zero double): 32
Enter the exponent (integer): -2
Result is : 0.00097656250000000000
Enter the base (non-zero double): 32
Enter the exponent (integer): 1
Result is : 32.00000000000000000000
Enter the base (non-zero double): 32  32
Enter the exponent (integer): 0
Result is : 1.00000000000000000000
]0;oarbelwo@compute:~/courses/cs2211/Asn/asn2[?2004h[oarbelwo@compute asn2]$ exit
[?2004lexit

Script done on 2023-02-08 11:52:05-05:00 [COMMAND_EXIT_CODE="0"]
